In [ ]:
import torch

In [ ]:
t1=torch.tensor(4.0)
t1

tensor(4.)

In [ ]:
t1.dtype

torch.float32

In [ ]:
s = {1., 2, 3, 4}

# Convert set to list and then create a tensor
t2 = torch.tensor(list(s))
print(t2)

tensor([1., 2., 3., 4.])


In [ ]:
t2.dtype

torch.float32

In [ ]:
t3=torch.tensor([[5.,6],
                 [7, 8],
                 [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [ ]:
t=torch.tensor([1.,2,3,4])
t


tensor([1., 2., 3., 4.])

In [ ]:
t4=torch.tensor([
    [[11,12,13],
     [13, 14, 15]],
    [[15,16, 17],
     [17,18, 19.]]
])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [ ]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [ ]:
t4.shape

torch.Size([2, 2, 3])

In [ ]:
t3.shape

torch.Size([3, 2])

improper size tensor does not exist

Tensor operations and gradients

In [ ]:
x=torch.tensor(3.)
w=torch.tensor(4., requires_grad=True)
b=torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
y=w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
#computing derivatives
y.backward()

derivative of y w.r.t the input tensors are stored in the .grad property

In [ ]:
print(x.grad)
print(w.grad)
print(b.grad)

None
tensor(3.)
tensor(1.)


Tensor Functions


In [ ]:
#create a tensor with a fixed value for every elemet
t6=torch.full((3,2), 42)
#shape and value
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [ ]:
#concatenate
t7=torch.cat((t3, t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [ ]:
#computing the sin
t8=torch.sin(t7)
t8


tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [ ]:
#change shape of a tensor
t9=t8.reshape(3, 2,2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

Interoperablity with Numpy

In [ ]:
import numpy as np
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [ ]:
#convert numoy to Pytorch tensor
y=torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [ ]:
x.dtype, y.dtype

(dtype('int64'), torch.int64)

In [ ]:
#convert tensor into numpy
z=y.numpy()
z

array([[1, 2],
       [3, 4]])